### ISSUE TITLE
Package hooks help for noobs

### ISSUE THREAD

**Issue by zbeekman** [purcell/osx-location#3]
Hi,
It might be nice to include both on the github README and in the melpa description the hook that most people are going to want to use with this package, something like:

```lisp
(if (eq system-type 'darwin)
   (progn (add-hook 'osx-location-changed-hook
		     (lambda()
		       (setq calendar-latitude osx-location-latitude)
		       (setq calendar-longitude osx-location-longitude)
		       (setq calendar-location-name (concat (number-to-string
	 osx-location-latitude) ", " (number-to-string osx-location-longitude)))))
  ))
```

**Comment by purcell** [comment]
Done, thanks - I used a different formulation of your example code, which I think should work the same, but is slightly neater. Let me know if I messed something up!

**Comment by zbeekman** [comment]
looks good to me, but I’m going to stick with my formula rather than test yours because I have a bunch of other stuff nested in the `(eq system-type ‘darwin` block :+1:

**Comment by purcell** [comment]
Better safe than sorry!
