### ISSUE TITLE
Location accuracy

### ISSUE THREAD

**Issue by usharf** [purcell/osx-location#5]
Shouldn't it be enough to compare location with one decimal point accuracy? Right now it triggers all the time even when computer is stationary.

```emacs-lisp
(6.161701/46.203227)
(6.161747/46.203241)
(6.16176/46.203241)
(6.161764/46.203241)
(6.161765/46.203243)
...
```

**Comment by purcell** [comment]
`osx-location` can't be responsible for deciding whether or not the location changes reported by the operating system are significant to a specific consumer.

But this is something you can handle yourself if you need to. Maybe write and use a hook function which stores the old location and then only performs the action you want when the location changes significantly enough for you to care?

**Comment by usharf** [comment]
Yes, I'm doing that right now, though thought we might set accuracy somehow and reduce callback overhead... (not sure what the impact is...)

**Comment by purcell** [comment]
Yep. I guess every OS X program which watches the location would have this problem, because the binary included in this package simply subscribes to the standard system location updates and passes them through to elisp land.

**Comment by usharf** [comment]
Got it. Thanks.
